# 1. Write a NumPy program to find the dot product of two arrays of different dimensions.

In [1]:
import numpy as np
# Define the two arrays
nums1 = np.array([[1, 2], [3, 4], [5, 6]])
nums2 = np.array([7, 8])
print("Original arrays:")
print(nums1)
print(nums2)
# Find the dot product
result = np.dot(nums1, nums2)
# Print the result
print("Dot product of the said two arrays:")
print(result)


Original arrays:
[[1 2]
 [3 4]
 [5 6]]
[7 8]
Dot product of the said two arrays:
[23 53 83]


# 2. Write a NumPy program to create a 3x3 identity matrix and stack it vertically and horizontally.

In [2]:
import numpy as np
# creating a 3x3 identity matrix
matrix = np.identity(3)
print("3x3 identity matrix:")
print(matrix)
# stacking the matrix vertically
vert_stack = np.vstack((matrix, matrix, matrix))
# stacking the matrix horizontally
horz_stack = np.hstack((matrix, matrix, matrix))
print("Vertical Stack:\n", vert_stack)
print("Horizontal Stack:\n", horz_stack)


3x3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Vertical Stack:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Horizontal Stack:
 [[1. 0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0. 1.]]


# 3. Write a NumPy program to create a 4x4 array with random values and find the sum of each row.

In [3]:
import numpy as np
# create a 4x4 array with random values
arr = np.random.rand(4, 4)
# find the sum of each row
row_sum = np.sum(arr, axis=1)
print("Original array:")
print(arr)
print("\nSum of each row:")
print(row_sum)


Original array:
[[0.57227048 0.47868409 0.12918839 0.71413717]
 [0.13561937 0.87597357 0.0505703  0.84571822]
 [0.69674063 0.03248769 0.26523163 0.51324124]
 [0.72645892 0.17359647 0.8157524  0.45964059]]

Sum of each row:
[1.89428014 1.90788145 1.50770118 2.17544838]


# 4. Write a NumPy program to create a 3x3 array with random values and subtract the mean of each row from each element.

In [4]:
import numpy as np
# create a 3x3 array with random values
arr = np.random.rand(3, 3)
print("Original array elements:")
print(arr)
# subtract the mean of each row from each element
row_means = np.mean(arr, axis=1, keepdims=True)
print("\nMean of each row:")
print(row_means)
arr_subtracted = arr - row_means
print("\nSubtract the mean of each row from each element:")
print(arr_subtracted)


Original array elements:
[[0.54792234 0.99516244 0.41118433]
 [0.44453278 0.38801061 0.31812652]
 [0.45456587 0.9392624  0.74453835]]

Mean of each row:
[[0.65142304]
 [0.38355664]
 [0.71278887]]

Subtract the mean of each row from each element:
[[-0.1035007   0.3437394  -0.2402387 ]
 [ 0.06097614  0.00445397 -0.06543012]
 [-0.258223    0.22647353  0.03174947]]


# 5. Write a NumPy program to create a 3x3 array with random values and subtract the mean of each column from each element.


In [5]:
import numpy as np
# Generate a 3x3 array with random values
nums = np.random.rand(3, 3)
print("Original array elements:")
print(nums)
# Compute the mean of each column
col_means = np.mean(nums, axis=0)
print("\nMean of each row:")
print(col_means)
# Subtract the mean of each column from each element
print("\nSubtract the mean of each row from each element:")
result = nums - col_means
print(result)


Original array elements:
[[0.98112504 0.9280902  0.4561258 ]
 [0.23048298 0.87340014 0.0744325 ]
 [0.46387807 0.00834419 0.55516174]]

Mean of each row:
[0.55849536 0.60327818 0.36190668]

Subtract the mean of each row from each element:
[[ 0.42262968  0.32481202  0.09421912]
 [-0.32801238  0.27012196 -0.28747418]
 [-0.0946173  -0.59493399  0.19325506]]


# 6. Write a NumPy program to create a 5x5 array with random values and normalize it row-wise.

In [6]:
import numpy as np
# create 5x5 array with random values
nums = np.random.rand(5, 5)
print("Original array elements:")
print(nums)
# normalize row-wise
norm_arr = nums / np.linalg.norm(nums, axis=1, keepdims=True)
print("\nNormalize Array row-wise:")
print(norm_arr)


Original array elements:
[[0.60890063 0.02397488 0.33613844 0.20594337 0.31237262]
 [0.21407151 0.07015954 0.38914237 0.49179808 0.87991309]
 [0.6439426  0.19422175 0.81319646 0.73988569 0.59187344]
 [0.69386816 0.98259713 0.33185964 0.02795749 0.16763217]
 [0.95332822 0.95576153 0.92036324 0.38878831 0.30788332]]

Normalize Array row-wise:
[[0.7706287  0.03034277 0.42541906 0.26064331 0.39534088]
 [0.19394696 0.06356394 0.35255966 0.44556485 0.79719373]
 [0.454042   0.13694517 0.57338239 0.52169118 0.4173282 ]
 [0.55097312 0.78024132 0.26351655 0.02219993 0.13311005]
 [0.55833963 0.55976476 0.5390329  0.22770324 0.18031928]]


# 7. Write a NumPy program to create a 5x5 array with random values and normalize it column-wise.

In [7]:
import numpy as np
# create a 5x5 array with random values
nums = np.random.rand(5, 5)
print("Original array elements:")
print(nums)
# compute the mean of each column
col_means = np.mean(nums, axis=0)

# normalize each column by subtracting its mean and dividing by its standard deviation
arr_normalized = (nums - col_means) / np.std(nums, axis=0)

print("Original Array:")
print(nums)
print("\nNormalized Array (column-wise):")
print(arr_normalized)


Original array elements:
[[0.20717974 0.31083774 0.92037686 0.45918772 0.51276593]
 [0.32820589 0.90760035 0.84106279 0.95657744 0.41470095]
 [0.51315323 0.35680825 0.90312162 0.64455118 0.9734274 ]
 [0.98211064 0.70510559 0.42674074 0.47482676 0.27801187]
 [0.03120904 0.21686173 0.12149491 0.64362612 0.04751738]]
Original Array:
[[0.20717974 0.31083774 0.92037686 0.45918772 0.51276593]
 [0.32820589 0.90760035 0.84106279 0.95657744 0.41470095]
 [0.51315323 0.35680825 0.90312162 0.64455118 0.9734274 ]
 [0.98211064 0.70510559 0.42674074 0.47482676 0.27801187]
 [0.03120904 0.21686173 0.12149491 0.64362612 0.04751738]]

Normalized Array (column-wise):
[[-0.63069926 -0.71836277  0.87629143 -0.98660229  0.21995378]
 [-0.25870077  1.55459953  0.62611913  1.79267279 -0.09968719]
 [ 0.30977251 -0.54326928  0.821865    0.04915709  1.72147128]
 [ 1.75120853  0.78333311 -0.68073483 -0.89921568 -0.54522269]
 [-1.171581   -1.07630059 -1.64354074  0.0439881  -1.29651519]]


# 8. Write a NumPy program to create a 3x3x3 array with random values and find the sum along the last axis.

In [8]:
import numpy as np
nums = np.random.rand(3, 3, 3)
print("Original array elements:")
print(nums)
sum_along_last_axis = np.sum(nums, axis=2)
print("\nSum along the last axis:")
print(sum_along_last_axis)


Original array elements:
[[[0.95283005 0.04955241 0.7836595 ]
  [0.30937864 0.07428143 0.98327484]
  [0.92082057 0.58597861 0.2621557 ]]

 [[0.75738979 0.55647454 0.34731738]
  [0.88486715 0.1405425  0.74260409]
  [0.80107172 0.75456547 0.23068748]]

 [[0.20769479 0.13335187 0.47828824]
  [0.0342953  0.82682006 0.44407393]
  [0.36128348 0.64279483 0.56678688]]]

Sum along the last axis:
[[1.78604196 1.36693491 1.76895489]
 [1.66118171 1.76801374 1.78632468]
 [0.81933489 1.30518929 1.57086519]]


# 9. Write a NumPy program to create a 5x5 array with random values and sort each row.

In [9]:
import numpy as np
# create a 5x5 array with random values
nums = np.random.rand(5, 5)
print("Original array elements:")
print(nums)
# sort each row
sorted_arr = np.sort(nums, axis=1)
print("\nSort each row of the said array:")
print(sorted_arr)


Original array elements:
[[0.26238345 0.75881033 0.15700121 0.35359174 0.15780135]
 [0.7079059  0.57773629 0.83020025 0.18876914 0.20593678]
 [0.58612782 0.24355176 0.30109946 0.70490139 0.13219213]
 [0.44279609 0.71818862 0.36457123 0.68900288 0.54053052]
 [0.00669318 0.40749457 0.52547109 0.57704708 0.04572941]]

Sort each row of the said array:
[[0.15700121 0.15780135 0.26238345 0.35359174 0.75881033]
 [0.18876914 0.20593678 0.57773629 0.7079059  0.83020025]
 [0.13219213 0.24355176 0.30109946 0.58612782 0.70490139]
 [0.36457123 0.44279609 0.54053052 0.68900288 0.71818862]
 [0.00669318 0.04572941 0.40749457 0.52547109 0.57704708]]


# 10. Write a NumPy program to create a 5x5 array with random values and sort each column.

In [10]:
import numpy as np
# create a 5x5 array with random values
nums = np.random.rand(5, 5)
print("Original array elements:")
print(nums)
# sort each column
arr_sorted = np.sort(nums, axis=0)
# print the sorted array
print("\nSort each column of the said array:")
print(arr_sorted)


Original array elements:
[[0.4337807  0.38888243 0.16788402 0.40970441 0.05396337]
 [0.5612265  0.64920327 0.07147919 0.48657981 0.56350602]
 [0.61517034 0.28976195 0.2614459  0.19024545 0.52945489]
 [0.81726725 0.73441184 0.87535953 0.3633898  0.40930659]
 [0.1975469  0.54474558 0.21316215 0.57665973 0.57562275]]

Sort each column of the said array:
[[0.1975469  0.28976195 0.07147919 0.19024545 0.05396337]
 [0.4337807  0.38888243 0.16788402 0.3633898  0.40930659]
 [0.5612265  0.54474558 0.21316215 0.40970441 0.52945489]
 [0.61517034 0.64920327 0.2614459  0.48657981 0.56350602]
 [0.81726725 0.73441184 0.87535953 0.57665973 0.57562275]]


# 11. Write a NumPy program to create a 5x5 array with random values and find the second-largest value in each row.

In [11]:
import numpy as np
# create a 5x5 array with random values
nums = np.random.rand(5, 5)
print("Original array elements:")
print(nums)
# find the second-largest value in each row
second_largest = np.partition(nums, -2, axis=1)[:, -2]
print("\nSecond-largest value in each row:")
print(second_largest)


Original array elements:
[[0.54525728 0.1573066  0.79666092 0.98373108 0.33188061]
 [0.49243768 0.49972551 0.97742797 0.40146745 0.71112427]
 [0.73846396 0.16122823 0.09863815 0.91897662 0.30047359]
 [0.29288219 0.08180685 0.56446474 0.41420359 0.77308773]
 [0.64236073 0.95482104 0.77249781 0.08562443 0.50300102]]

Second-largest value in each row:
[0.79666092 0.71112427 0.73846396 0.56446474 0.77249781]


# 12. Write a NumPy program to create a 5x5 array with random values and find the second-largest value in each column.

In [12]:
import numpy as np
# create a 5x5 array with random values
nums = np.random.rand(5, 5)
print("Original array elements:")
print(nums)
# find the indices of the second-largest value in each column
indices = np.argsort(nums, axis=0)[-2, :]
# get the second-largest value in each column using the indices
second_largest_values = nums[indices, np.arange(nums.shape[1])]
print("\nSecond-largest value in each column:")
print(second_largest_values)


Original array elements:
[[0.86217941 0.89346558 0.86229927 0.0922991  0.36971005]
 [0.6386859  0.98656647 0.06643242 0.12270325 0.0878116 ]
 [0.38517542 0.25628521 0.30643383 0.82468723 0.91637751]
 [0.11861636 0.11415444 0.48774704 0.82348061 0.65103237]
 [0.83246873 0.70059005 0.91393007 0.2275189  0.69511122]]

Second-largest value in each column:
[0.83246873 0.89346558 0.86229927 0.82348061 0.69511122]


# 13. Write a NumPy program to create a 5x5 array with random values and replace the maximum value with 0.

In [13]:
import numpy as np
nums = np.random.rand(5, 5)
print("Original array elements:")
print(nums)
max_value = np.max(nums)
nums[nums == max_value] = 0
print("\nSaid array after replacing the maximum value with 0:")
print(nums)


Original array elements:
[[0.29923481 0.76207372 0.41867681 0.83563488 0.22281252]
 [0.46652794 0.40250222 0.25733508 0.07271291 0.63972907]
 [0.29740919 0.54201703 0.28886218 0.42797893 0.6422026 ]
 [0.15769808 0.56047195 0.22899428 0.75360624 0.45792872]
 [0.91447775 0.97906225 0.98474326 0.60086906 0.47504474]]

Said array after replacing the maximum value with 0:
[[0.29923481 0.76207372 0.41867681 0.83563488 0.22281252]
 [0.46652794 0.40250222 0.25733508 0.07271291 0.63972907]
 [0.29740919 0.54201703 0.28886218 0.42797893 0.6422026 ]
 [0.15769808 0.56047195 0.22899428 0.75360624 0.45792872]
 [0.91447775 0.97906225 0.         0.60086906 0.47504474]]


# 14. Write a NumPy program to create a 5x5 array with random values and replace the minimum value with 0.

In [14]:
import numpy as np
# Create a 5x5 array with random values
nums = np.random.rand(5, 5)
print("Original array elements:")
print(nums)
# Find the minimum value in the array
min_val = nums.min()
# Replace the minimum value with 0
nums[nums == min_val] = 0
# Print the updated array
print("\nSaid array after replacing the minimum value with 0:")
print(nums)


Original array elements:
[[0.60465257 0.19212837 0.59935223 0.94025967 0.89896513]
 [0.80346808 0.44829793 0.91692804 0.17736588 0.90020644]
 [0.65209815 0.19112137 0.59341666 0.49510467 0.83633524]
 [0.74896576 0.11017847 0.475337   0.38238192 0.9499203 ]
 [0.86755893 0.14619528 0.72313979 0.08128489 0.97397941]]

Said array after replacing the minimum value with 0:
[[0.60465257 0.19212837 0.59935223 0.94025967 0.89896513]
 [0.80346808 0.44829793 0.91692804 0.17736588 0.90020644]
 [0.65209815 0.19112137 0.59341666 0.49510467 0.83633524]
 [0.74896576 0.11017847 0.475337   0.38238192 0.9499203 ]
 [0.86755893 0.14619528 0.72313979 0.         0.97397941]]


# 15. Write a NumPy program to create a 5x5 array with random values and calculate the exponential of each element.

In [15]:
import numpy as np
nums = np.random.rand(5, 5)
print("Original array elements:")
print(nums)
exp_arr = np.exp(nums)
print("\nExponential of each element of the said array:")
print(exp_arr)


Original array elements:
[[0.71697549 0.03089944 0.40190484 0.57555026 0.0644768 ]
 [0.66653278 0.13652013 0.51986404 0.07080839 0.13284185]
 [0.64008385 0.53173932 0.44172422 0.42410082 0.19809962]
 [0.26199391 0.3303792  0.51707868 0.08316576 0.52952929]
 [0.1986937  0.1095897  0.42576756 0.41704225 0.05376008]]

Exponential of each element of the said array:
[[2.04822894 1.03138178 1.49466909 1.77810868 1.06660084]
 [1.94747327 1.14627795 1.68179897 1.07337553 1.14206936]
 [1.89663991 1.70188987 1.55538673 1.52821567 1.21908384]
 [1.29951863 1.39149568 1.67712109 1.08672193 1.69813279]
 [1.21980829 1.11582016 1.53076492 1.51746663 1.0552314 ]]


# NumPy: Advanced Exercises is Completed.