# 1. Write a NumPy program to add, subtract, multiply, divide arguments element-wise.
Expected Output:
Add:
5.0
Subtract:
-3.0
Multiply:
4.0
Divide:
0.25

In [1]:
import numpy as np
print("Add:")
print(np.add(1.0, 4.0))
print("Subtract:")
print(np.subtract(1.0, 4.0))
print("Multiply:")
print(np.multiply(1.0, 4.0))
print("Divide:")
print(np.divide(1.0, 4.0))


Add:
5.0
Subtract:
-3.0
Multiply:
4.0
Divide:
0.25


# 2. Write a NumPy program to compute logarithm of the sum of exponentiations of the inputs, sum of exponentiations of the inputs in base-2.
Expected Output:
Logarithm of the sum of exponentiations:
-113.876491681
Logarithm of the sum of exponentiations of the inputs in base-2:
-113.599555228

In [2]:
import numpy as np
l1 = np.log(1e-50)
l2 = np.log(2.5e-50)
print("Logarithm of the sum of exponentiations:")
print(np.logaddexp(l1, l2))
print("Logarithm of the sum of exponentiations of the inputs in base-2:")
print(np.logaddexp2(l1, l2))


Logarithm of the sum of exponentiations:
-113.87649168120691
Logarithm of the sum of exponentiations of the inputs in base-2:
-113.59955522772194


# 3. Write a NumPy program to get true division of the element-wise array inputs.
Expected Output:
Original array:
[0 1 2 3 4 5 6 7 8 9]
Division of the array inputs, element-wise:
[ 0. 0.33333333 0.66666667 1. 1.33333333 1.6666666
7 2. 2.33333333 2.66666667 3. ]

In [3]:
import numpy as np
x = np.arange(10)
print("Original array:")
print(x)
print("Division of the array inputs, element-wise:")
print(np.true_divide(x, 3))


Original array:
[0 1 2 3 4 5 6 7 8 9]
Division of the array inputs, element-wise:
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.        ]


# 4. Write a NumPy program to get the largest integer smaller or equal to the division of the inputs.
Expected Output:
Original array:
[1.0, 2.0, 3.0, 4.0]
Largest integer smaller or equal to the division of the inputs:
[ 0. 1. 2. 2.]

In [4]:
import numpy as np
x = [1., 2., 3., 4.]
print("Original array:")
print(x)
print("Largest integer smaller or equal to the division of the inputs:")
print(np.floor_divide(x, 1.5))


Original array:
[1.0, 2.0, 3.0, 4.0]
Largest integer smaller or equal to the division of the inputs:
[0. 1. 2. 2.]


# 5. Write a NumPy program to get the powers of an array values element-wise.
Note: First array elements raised to powers from second array
Expected Output:
Original array
[0 1 2 3 4 5 6]
First array elements raised to powers from second array, element-wise:
[ 0 1 8 27 64 125 216]

In [5]:
import numpy as np
x = np.arange(7)
print("Original array")
print(x)
print("First array elements raised to powers from second array, element-wise:")
print(np.power(x, 3))


Original array
[0 1 2 3 4 5 6]
First array elements raised to powers from second array, element-wise:
[  0   1   8  27  64 125 216]


# 6. Write a NumPy program to get the element-wise remainder of an array of division.
Sample Output:
Original array:
[0 1 2 3 4 5 6]
Element-wise remainder of division:
[0 1 2 3 4 0 1]

In [6]:
import numpy as np
x = np.arange(7)
print("Original array:")
print(x)
print("Element-wise remainder of division:")
print(np.remainder(x, 5))


Original array:
[0 1 2 3 4 5 6]
Element-wise remainder of division:
[0 1 2 3 4 0 1]


# 7. Write a NumPy program to calculate the absolute value element-wise.
Sample output:
Original array:
[ -10.2 122.2 0.2]
Element-wise absolute value:
[ 10.2 122.2 0.2]

In [7]:
import numpy as np
x = np.array([-10.2, 122.2, .20])
print("Original array:")
print(x)
print("Element-wise absolute value:")
print(np.absolute(x))


Original array:
[-10.2 122.2   0.2]
Element-wise absolute value:
[ 10.2 122.2   0.2]


# 8. Write a NumPy program to round array elements to the given number of decimals.
Sample Output:
[ 1. 2. 2.]
[ 0.3 0.5 0.6]
[ 0. 2. 2. 4. 4.]

In [8]:
import numpy as np
x = np.round([1.45, 1.50, 1.55])
print(x)
x = np.round([0.28, .50, .64], decimals=1)
print(x)
x = np.round([.5, 1.5, 2.5, 3.5, 4.5]) # rounds to nearest even value
print(x)


[1. 2. 2.]
[0.3 0.5 0.6]
[0. 2. 2. 4. 4.]


# 9. Write a NumPy program to round elements of the array to the nearest integer.
Sample Output:
Original array:
[-0.7 -1.5 -1.7 0.3 1.5 1.8 2. ]
Round elements of the array to the nearest integer:
[-1. -2. -2. 0. 2. 2. 2.]

In [9]:
import numpy as np
x = np.array([-.7, -1.5, -1.7, 0.3, 1.5, 1.8, 2.0])
print("Original array:")
print(x)
x = np.rint(x)
print("Round elements of the array to the nearest integer:")
print(x)


Original array:
[-0.7 -1.5 -1.7  0.3  1.5  1.8  2. ]
Round elements of the array to the nearest integer:
[-1. -2. -2.  0.  2.  2.  2.]


# 10. Write a NumPy program to get the floor, ceiling and truncated values of the elements of a numpy array.
Sample Output:
Original array:
[-1.6 -1.5 -0.3 0.1 1.4 1.8 2. ]
Floor values of the above array elements:
[-2. -2. -1. 0. 1. 1. 2.]
Ceil values of the above array elements:
[-1. -1. -0. 1. 2. 2. 2.]
Truncated values of the above array elements:
[-1. -1. -0. 0. 1. 1. 2.]

In [10]:
import numpy as np
x = np.array([-1.6, -1.5, -0.3, 0.1, 1.4, 1.8, 2.0])
print("Original array:")
print(x)
print("Floor values of the above array elements:")
print(np.floor(x))
print("Ceil values of the above array elements:")
print(np.ceil(x))
print("Truncated values of the above array elements:")
print(np.trunc(x))


Original array:
[-1.6 -1.5 -0.3  0.1  1.4  1.8  2. ]
Floor values of the above array elements:
[-2. -2. -1.  0.  1.  1.  2.]
Ceil values of the above array elements:
[-1. -1. -0.  1.  2.  2.  2.]
Truncated values of the above array elements:
[-1. -1. -0.  0.  1.  1.  2.]


# 11. Write a NumPy program to multiply a 5x3 matrix by a 3x2 matrix and create a real matrix product.
Sample output:
First array:
[[ 0.44349753 0.81043761 0.00771825]
[ 0.64004088 0.86774612 0.19944667]
[ 0.61520091 0.24796788 0.93798297]
[ 0.22156999 0.61318856 0.82348994]
[ 0.91324026 0.13411297 0.00622696]]
Second array:
[[ 0.73873542 0.06448186]
[ 0.90974982 0.06409165]
[ 0.22321268 0.39147412]]
Dot product of two arrays:
[[ 1.06664562 0.08356133]
[ 1.30677176 0.17496452]
[ 0.88942914 0.42275803]
[ 0.90534318 0.37596252]
[ 0.79804212 0.06992065]]

In [11]:
import numpy as np
x = np.random.random((5,3))
print("First array:")
print(x)
y = np.random.random((3,2))
print("Second array:")
print(y)
z = np.dot(x, y)
print("Dot product of two arrays:")
print(z)


First array:
[[0.48739702 0.1069933  0.30496585]
 [0.64290328 0.4893841  0.48895402]
 [0.3648529  0.40595255 0.07698448]
 [0.42416648 0.60870901 0.54299847]
 [0.3476861  0.81870074 0.96526252]]
Second array:
[[0.22681599 0.70210858]
 [0.99632363 0.44762599]
 [0.87510391 0.28619153]]
Dot product of two arrays:
[[0.48402619 0.47737725]
 [1.06129126 0.81038344]
 [0.55458401 0.45991357]
 [1.177859   0.72568646]
 [1.73925667 0.88683508]]


# 12. Write a NumPy program to multiply a matrix by another matrix of complex numbers and create a new matrix of complex numbers.
Sample output:
First array:
[ 1.+2.j 3.+4.j]
Second array:
[ 5.+6.j 7.+8.j]
Product of above two arrays:
(70-8j)

In [12]:
import numpy as np
x = np.array([1+2j,3+4j])
print("First array:")
print(x)
y = np.array([5+6j,7+8j])
print("Second array:")
print(y)
z = np.vdot(x, y)
print("Product of above two arrays:")
print(z)


First array:
[1.+2.j 3.+4.j]
Second array:
[5.+6.j 7.+8.j]
Product of above two arrays:
(70-8j)


# 13. Write a NumPy program to create an inner product of two arrays.
Sample Output:
Array x:
[[[ 0 1 2 3]
[ 4 5 6 7]
[ 8 9 10 11]]
[[12 13 14 15]
[16 17 18 19]
[20 21 22 23]]]
Array y:
[0 1 2 3]
Inner of x and y arrays:
[[ 14 38 62]
[ 86 110 134]]

In [13]:
import numpy as np
x = np.arange(24).reshape((2,3,4))
print("Array x:")
print(x)
print("Array y:")
y = np.arange(4)
print(y)
print("Inner of x and y arrays:")
print(np.inner(x, y))


Array x:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Array y:
[0 1 2 3]
Inner of x and y arrays:
[[ 14  38  62]
 [ 86 110 134]]


# 14. Write a NumPy program to generate inner, outer, and cross products of matrices and vectors.
Expected Output:
Matrices and vectors.
x:
[ 1. 4. 0.]
y:
[ 2. 2. 1.]
Inner product of x and y:
10.0
Outer product of x and y:
[[ 2. 2. 1.]
[ 8. 8. 4.]
[ 0. 0. 0.]]
Cross product of x and y:
[ 4. -1. -6.]

In [14]:
import numpy as np
x = np.array([1, 4, 0], float)
y = np.array([2, 2, 1], float)
print("Matrices and vectors.")
print("x:")
print(x)
print("y:")
print(y)
print("Inner product of x and y:")
print(np.inner(x, y))
print("Outer product of x and y:")
print(np.outer(x, y))
print("Cross product of x and y:")
print(np.cross(x, y))


Matrices and vectors.
x:
[1. 4. 0.]
y:
[2. 2. 1.]
Inner product of x and y:
10.0
Outer product of x and y:
[[2. 2. 1.]
 [8. 8. 4.]
 [0. 0. 0.]]
Cross product of x and y:
[ 4. -1. -6.]


# 15. Write a NumPy program to generate a matrix product of two arrays.
Sample Output:
Matrices and vectors.
x:
[[1, 0], [1, 1]]
y:
[[3, 1], [2, 2]]
Matrix product of above two arrays:
[[3 1]
[5 3]]

In [15]:
import numpy as np
x = [[1, 0], [1, 1]]
y = [[3, 1], [2, 2]]
print("Matrices and vectors.")
print("x:")
print(x)
print("y:")
print(y)
print("Matrix product of above two arrays:")
print(np.matmul(x, y))


Matrices and vectors.
x:
[[1, 0], [1, 1]]
y:
[[3, 1], [2, 2]]
Matrix product of above two arrays:
[[3 1]
 [5 3]]


# 16. Write a NumPy program to find the roots of the following polynomials.
a) x2 - 4x + 7.
b) x4 - 11x3 + 9x2 + 11x ? 10
Sample output:
Roots of the first polynomial:
[ 1. 1.]
Roots of the second polynomial:
[ 11.04461946+0.j -0.87114210+0.j 0.91326132+0.4531004j
0.91326132-0.4531004j]

In [16]:
import numpy as np
print("Roots of the first polynomial:")
print(np.roots([1, -2, 1]))
print("Roots of the second polynomial:")
print(np.roots([1, -12, 10, 7, -10]))


Roots of the first polynomial:
[1. 1.]
Roots of the second polynomial:
[11.04461946+0.j        -0.8711421 +0.j         0.91326132+0.4531004j
  0.91326132-0.4531004j]


# 17. Write a NumPy program to compute the following polynomial values.
Sample output:
Polynomial value when x = 2:
1
Polynomial value when x = 3:
-142

In [17]:
import numpy as np
print("Polynomial value when x = 2:")
print(np.polyval([1, -2, 1], 2))
print("Polynomial value when x = 3:")
print(np.polyval([1, -12, 10, 7, -10], 3))


Polynomial value when x = 2:
1
Polynomial value when x = 3:
-142


# 18. Write a NumPy program to add one polynomial to another, subtract one polynomial from another, multiply one polynomial by another and divide one polynomial by another.
Sample output:
Add one polynomial to another:
[ 40. 60. 80.]
Subtract one polynomial from another:
[-20. -20. -20.]
Multiply one polynomial by another:
[ 300. 1000. 2200. 2200. 1500.]
Divide one polynomial by another:
(array([ 0.6]), array([-8., -4.]))

In [18]:
from numpy.polynomial import polynomial as P
x = (10,20,30)
y = (30,40,50)
print("Add one polynomial to another:")
print(P.polyadd(x,y))
print("Subtract one polynomial from another:")
print(P.polysub(x,y))
print("Multiply one polynomial by another:")
print(P.polymul(x,y))
print("Divide one polynomial by another:")
print(P.polydiv(x,y))


Add one polynomial to another:
[40. 60. 80.]
Subtract one polynomial from another:
[-20. -20. -20.]
Multiply one polynomial by another:
[ 300. 1000. 2200. 2200. 1500.]
Divide one polynomial by another:
(array([0.6]), array([-8., -4.]))


# 19. Write a NumPy program to calculate mean across dimension, in a 2D numpy array.
Sample output:
Original array:
[[10 30]
[20 60]]
Mean of each column:
[ 15. 45.]
Mean of each row:
[ 20. 40.]

In [19]:
import numpy as np
x = np.array([[10, 30], [20, 60]])
print("Original array:")
print(x)
print("Mean of each column:")
print(x.mean(axis=0))
print("Mean of each row:")
print(x.mean(axis=1))


Original array:
[[10 30]
 [20 60]]
Mean of each column:
[15. 45.]
Mean of each row:
[20. 40.]


# 20. Write a NumPy program to create a random array with 1000 elements and compute the average, variance, standard deviation of the array elements.
Sample output:
Average of the array elements:
-0.0255137240796
Standard deviation of the array elements:
0.984398282476
Variance of the array elements:
0.969039978542

In [20]:
import numpy as np
x = np.random.randn(1000)
print("Average of the array elements:")
mean = x.mean()
print(mean)
print("Standard deviation of the array elements:")
std = x.std()
print(std)
print("Variance of the array elements:")
var = x.var()
print(var)


Average of the array elements:
-0.006025592881094063
Standard deviation of the array elements:
1.0138833407478522
Variance of the array elements:
1.0279594286460256


# 21. Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in degrees.
Sample output:
sine: array of angles given in degrees
[ 0. 0.5 0.70710678 0.8660254 1. ]
cosine: array of angles given in degrees
[ 1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
6.12323400e-17]
tangent: array of angles given in degrees
[ 0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
1.63312394e+16]

In [21]:
import numpy as np
print("sine: array of angles given in degrees")
print(np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print("cosine: array of angles given in degrees")
print(np.cos(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print("tangent: array of angles given in degrees")
print(np.tan(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))


sine: array of angles given in degrees
[0.         0.5        0.70710678 0.8660254  1.        ]
cosine: array of angles given in degrees
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
tangent: array of angles given in degrees
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


# 22. Write a NumPy program to calculate inverse sine, inverse cosine, and inverse tangent for all elements in a given array.
Sample output:
Inverse sine: [-1.57079633 0. 1.57079633]
Inverse cosine: [3.14159265 1.57079633 0. ]
Inverse tangent: [-0.78539816 0. 0.78539816]

In [22]:
import numpy as np
x = np.array([-1., 0, 1.])
print("Inverse sine:", np.arcsin(x))
print("Inverse cosine:", np.arccos(x))
print("Inverse tangent:", np.arctan(x))


Inverse sine: [-1.57079633  0.          1.57079633]
Inverse cosine: [3.14159265 1.57079633 0.        ]
Inverse tangent: [-0.78539816  0.          0.78539816]


# 23. Write a NumPy program to convert angles from radians to degrees for all elements in a given array.
Input: [-np.pi, -np.pi/2, np.pi/2, np.pi]
Sample output:
[-180. -90. 90. 180.]

In [23]:
import numpy as np
x = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])
r1 = np.degrees(x)
r2 = np.rad2deg(x)
assert np.array_equiv(r1, r2)
print(r1)


[-180.  -90.   90.  180.]


# 24. Write a NumPy program to convert angles from degrees to radians for all elements in a given array.
Input: Input: [-180., -90., 90., 180.]
Sample output:
[-3.14159265 -1.57079633 1.57079633 3.14159265]

In [24]:
import numpy as np
x = np.array([-180.,  -90.,   90.,  180.])
r1 = np.radians(x)
r2 = np.deg2rad(x)
assert np.array_equiv(r1, r2)
print(r1)


[-3.14159265 -1.57079633  1.57079633  3.14159265]


# 25. Write a NumPy program to calculate hyperbolic sine, hyperbolic cosine, and hyperbolic tangent for all elements in a given array.
Input: Input: Input: [-1., 0, 1.]
Sample output:
[-1.17520119 0. 1.17520119]
[1.54308063 1. 1.54308063]
[-0.76159416 0. 0.76159416]

In [25]:
import numpy as np
x = np.array([-1., 0, 1.])
print(np.sinh(x))
print(np.cosh(x))
print(np.tanh(x))


[-1.17520119  0.          1.17520119]
[1.54308063 1.         1.54308063]
[-0.76159416  0.          0.76159416]


# 26. Write a NumPy program to calculate round, floor, ceiling, truncated and round (to the given number of decimals) of the input, element-wise of a given array.
Sample output:
Original array:
[ 3.1 3.5 4.5 2.9 -3.1 -3.5 -5.9]
around: [ 3. 4. 4. 3. -3. -4. -6.]
floor: [ 3. 3. 4. 2. -4. -4. -6.]
ceil: [ 4. 4. 5. 3. -3. -3. -5.]
trunc: [ 3. 3. 4. 2. -3. -3. -5.]
round: [3.0, 4.0, 4.0, 3.0, -3.0, -4.0, -6.0]

In [26]:
import numpy as np
x = np.array([3.1, 3.5, 4.5, 2.9, -3.1, -3.5, -5.9])
print("Original array: ")
print(x)
r1 = np.around(x)
r2 = np.floor(x)
r3 = np.ceil(x)
r4 = np.trunc(x)
r5 = [round(elem) for elem in x]

print("\naround:   ", r1)
print("floor:    ",r2)
print("ceil:     ",r3)
print("trunc:    ",r4)
print("round:    ",r5)


Original array: 
[ 3.1  3.5  4.5  2.9 -3.1 -3.5 -5.9]

around:    [ 3.  4.  4.  3. -3. -4. -6.]
floor:     [ 3.  3.  4.  2. -4. -4. -6.]
ceil:      [ 4.  4.  5.  3. -3. -3. -5.]
trunc:     [ 3.  3.  4.  2. -3. -3. -5.]
round:     [3, 4, 4, 3, -3, -4, -6]


# 27. Write a NumPy program to calculate cumulative sum of the elements along a given axis, sum over rows for each of the 3 columns and sum over columns for each of the 2 rows of a given 3x3 array.
Sample output:
Original array:
[[1 2 3]
[4 5 6]]
Cumulative sum of the elements along a given axis:
[ 1 3 6 10 15 21]
Sum over rows for each of the 3 columns:
[[1 2 3]
[5 7 9]]
Sum over columns for each of the 2 rows:
[[ 1 3 6]
[ 4 9 15]]

In [27]:
import numpy as np
x = np.array([1, 3, 5, 7, 0])
print("Original array: ")
print(x)
r1 = np.ediff1d(x, to_begin=[0, 0], to_end=[200])
r2 = np.insert(np.append(np.diff(x), 200), 0, [0, 0])
assert np.array_equiv(r1, r2)
print("Difference between neighboring elements, element-wise, and prepend [0, 0] and append[200] to the said array:")
print(r2)


Original array: 
[1 3 5 7 0]
Difference between neighboring elements, element-wise, and prepend [0, 0] and append[200] to the said array:
[  0   0   2   2   2  -7 200]


# 28. Write a NumPy program to calculate cumulative product of the elements along a given axis, sum over rows for each of the 3 columns and product over columns for each of the 2 rows of a given 3x3 array.
Sample output:
Original array:
[[1 2 3]
[4 5 6]]
Cumulative product of the elements along a given axis:
[ 1 2 6 24 120 720]
Product over rows for each of the 3 columns:
[[ 1 2 3]
[ 4 10 18]]
Product over columns for each of the 2 rows:
[[ 1 2 6]
[ 4 20 120]]

In [28]:
import numpy as np
x = np.array([[1,2,3], [4,5,6]])
print("Original array: ")
print(x)
print("Cumulative product  of the elements along a given axis:")
r = np.cumprod(x)
print(r)
print("\nProduct over rows for each of the 3 columns:")
r = np.cumprod(x,axis=0) 
print(r)
print("\nProduct  over columns for each of the 2 rows:")
r = np.cumprod(x,axis=1) 
print(r)


Original array: 
[[1 2 3]
 [4 5 6]]
Cumulative product  of the elements along a given axis:
[  1   2   6  24 120 720]

Product over rows for each of the 3 columns:
[[ 1  2  3]
 [ 4 10 18]]

Product  over columns for each of the 2 rows:
[[  1   2   6]
 [  4  20 120]]


# 29. Write a NumPy program to calculate the difference between neighboring elements, element-wise of a given array.
Sample output:
Original array:
[1 3 5 7 0]
Difference between neighboring elements, element-wise of the said array.
[ 2 2 2 -7]

In [29]:
import numpy as np
x = np.array([1, 3, 5, 7, 0])
print("Original array: ")
print(x)
print("Difference between neighboring elements, element-wise of the said array.")
print(np.diff(x))


Original array: 
[1 3 5 7 0]
Difference between neighboring elements, element-wise of the said array.
[ 2  2  2 -7]


# 30. Write a NumPy program to calculate the difference between neighboring elements, element-wise, and prepend [0, 0] and append[200] to a given array.
Sample output:
Original array:
[1 3 5 7 0]
Difference between neighboring elements, element-wise, and prepend [0, 0] and append[200] to the said array:
[ 0 0 2 2 2 -7 200]

In [30]:
import numpy as np
x = np.array([1, 3, 5, 7, 0])
print("Original array: ")
print(x)
r1 = np.ediff1d(x, to_begin=[0, 0], to_end=[200])
r2 = np.insert(np.append(np.diff(x), 200), 0, [0, 0])
assert np.array_equiv(r1, r2)
print("Difference between neighboring elements, element-wise, and prepend [0, 0] and append[200] to the said array:")
print(r2)


Original array: 
[1 3 5 7 0]
Difference between neighboring elements, element-wise, and prepend [0, 0] and append[200] to the said array:
[  0   0   2   2   2  -7 200]


# 31. Write a NumPy program to compute ex, element-wise of a given array.
Sample output:
Original array:
[1. 2. 3. 4.]
e^x, element-wise of the said:
[ 2.7182817 7.389056 20.085537 54.59815 ]

In [31]:
import numpy as np
x = np.array([1., 2., 3., 4.], np.float32)
print("Original array: ")
print(x)
print("\ne^x, element-wise of the said:")
r = np.exp(x)
print(r)


Original array: 
[1. 2. 3. 4.]

e^x, element-wise of the said:
[ 2.718282   7.3890557 20.085537  54.59815  ]


# 32. Write a NumPy program to calculate exp(x) - 1 for all elements in a given array.
Sample output:
Original array: [1. 2. 3. 4.] exp(x)-1 for all elements of the said array: [ 1.7182817 6.389056 19.085537 53.59815 ]

In [32]:
import numpy as np
x = np.array([1., 2., 3., 4.], np.float32)
print("Original array: ")
print(x)
print("\nexp(x)-1 for all elements of the said array:")
r1 = np.expm1(x)
r2 = np.exp(x) - 1.
assert np.allclose(r1, r2)
print(r1)


Original array: 
[1. 2. 3. 4.]

exp(x)-1 for all elements of the said array:
[ 1.7182817  6.389056  19.085537  53.59815  ]


# 33. Write a NumPy program to calculate 2p for all elements in a given array.
Sample output:
Original array:
[1. 2. 3. 4.]
2^p for all the elements of the said array:
[ 2. 4. 8. 16.]

In [33]:
import numpy as np
x = np.array([1., 2., 3., 4.], np.float32)
print("Original array: ")
print(x)
print("\n2^p for all the elements of the said array:")
r1 = np.exp2(x)
r2 = 2 ** x
assert np.allclose(r1, r2)
print(r1)


Original array: 
[1. 2. 3. 4.]

2^p for all the elements of the said array:
[ 2.  4.  8. 16.]


# 34. Write a NumPy program to compute natural, base 10, and base 2 logarithms for all elements in a given array.
Sample output:
Original array:
Original array:
[1. 2.71828183 7.3890561 ]
Natural log = [0. 1. 2.]
Common log = [0. 0.43429448 0.86858896]
Base 2 log = [0. 1.44269504 2.88539008]

In [34]:
import numpy as np
x = np.array([1, np.e, np.e**2])
print("Original array: ")
print(x)
print("\nNatural log =", np.log(x))
print("Common log =", np.log10(x))
print("Base 2 log =", np.log2(x))


Original array: 
[1.         2.71828183 7.3890561 ]

Natural log = [0. 1. 2.]
Common log = [0.         0.43429448 0.86858896]
Base 2 log = [0.         1.44269504 2.88539008]


# 35. Write a NumPy program to compute the natural logarithm of one plus each element of a given array in floating-point accuracy.
Sample output:
Original array:
[1.e-099 1.e-100]
Natural logarithm of one plus each element:
[1.e-099 1.e-100]

In [35]:
import numpy as np
x = np.array([1e-99, 1e-100])
print("Original array: ")
print(x)
print("\nNatural logarithm of one plus each element:")
print(np.log1p(x))


Original array: 
[1.e-099 1.e-100]

Natural logarithm of one plus each element:
[1.e-099 1.e-100]


# 36. Write a NumPy program to check element-wise True/False of a given array where signbit is set.
Sample array: [-4, -3, -2, -1, 0, 1, 2, 3, 4]
Sample output:
Original array:
[-4 -3 -2 -1 0 1 2 3 4]
[ True True True True False False False False False]

In [36]:
import numpy as np
x = np.array([-4, -3, -2, -1, 0, 1, 2, 3, 4])
print("Original array: ")
print(x)
r1 = np.signbit(x)
r2 = x < 0
assert np.array_equiv(r1, r2)
print(r1)


Original array: 
[-4 -3 -2 -1  0  1  2  3  4]
[ True  True  True  True False False False False False]


# 37. Write a NumPy program to change the sign of a given array to that of a given array, element-wise.
Sample output:
Original array:
[-1 0 1 2]
Sign of x1 to that of x2, element-wise:
[-1. 0. 1. 2.]

In [37]:
import numpy as np
x1 = np.array([-1, 0, 1, 2])
print("Original array: ")
print(x1)
x2 = -2.1
print("\nSign of x1 to that of x2, element-wise:")
print(np.copysign(x1, x2))


Original array: 
[-1  0  1  2]

Sign of x1 to that of x2, element-wise:
[-1. -0. -1. -2.]


# 38. Write a NumPy program to compute numerical negative value for all elements in a given array.
Sample output:
Original array:
[ 0 1 -1]
Numerical negative value for all elements of the said array:
[ 0 -1 1]

In [38]:
import numpy as np
x = np.array([0, 1, -1])
print("Original array: ")
print(x)
r1 = np.negative(x)
r2 = -x
assert np.array_equal(r1, r2)
print("Numerical negative value for all elements of the said array:")
print(r1)


Original array: 
[ 0  1 -1]
Numerical negative value for all elements of the said array:
[ 0 -1  1]


# 39. Write a NumPy program to compute the reciprocal for all elements in a given array.
Sample output:
Original array:
[1. 2. 0.2 0.3]
Reciprocal for all elements of the said array:
[1. 0.5 5. 3.33333333]

In [39]:
import numpy as np
x = np.array([1., 2., .2, .3])
print("Original array: ")
print(x)
r1 = np.reciprocal(x)
r2 = 1/x
assert np.array_equal(r1, r2)
print("Reciprocal for all elements of the said array:")
print(r1)


Original array: 
[1.  2.  0.2 0.3]
Reciprocal for all elements of the said array:
[1.         0.5        5.         3.33333333]


# 40. Write a NumPy program to compute xy, element-wise where x, y are two given arrays.
Sample output:
Array1:
[[1 2]
[3 4]]
Array1:
[[1 2]
[1 2]]
Result- x^y:
[[ 1 4]
[ 3 16]]

In [40]:
import numpy as np
x = np.array([[1, 2], [3, 4]])
y = np.array([[1, 2], [1, 2]])
print("Array1: ")
print(x)
print("Array1: ")
print(y)
print("Result- x^y:")
r1 = np.power(x, y)
print(r1)


Array1: 
[[1 2]
 [3 4]]
Array1: 
[[1 2]
 [1 2]]
Result- x^y:
[[ 1  4]
 [ 3 16]]


# 41. Write a NumPy program to compute an element-wise indication of the sign for all elements in a given array.
Sample output:
Original array;
[ 1 3 5 0 -1 -7 0 5]
Element-wise indication of the sign for all elements of the said array:
[ 1 1 1 0 -1 -1 0 1]

In [41]:
import numpy as np
x = np.array([1, 3, 5, 0, -1, -7, 0, 5])
print("Original array;")
print(x)
r1 = np.sign(x)
r2 = np.copy(x)
r2[r2 > 0] = 1
r2[r2 < 0] = -1
assert np.array_equal(r1, r2)
print("Element-wise indication of the sign for all elements of the said array:")
print(r1)


Original array;
[ 1  3  5  0 -1 -7  0  5]
Element-wise indication of the sign for all elements of the said array:
[ 1  1  1  0 -1 -1  0  1]


# NumPy: Mathematics Exercises is Completed.