# 1. Write a NumPy program to concatenate element-wise two arrays of string.
Expected Output:
Array1:
['Python' 'PHP']
Array2:
[' Java' ' C++']
new array:
['Python Java' 'PHP C++']

In [1]:
import numpy as np
x1 = np.array(['Python', 'PHP'], dtype=np.str)
x2 = np.array([' Java', ' C++'], dtype=np.str)
print("Array1:")
print(x1)
print("Array2:")
print(x2)
new_array = np.char.add(x1, x2)
print("new array:")
print(new_array)


Array1:
['Python' 'PHP']
Array2:
[' Java' ' C++']
new array:
['Python Java' 'PHP C++']


C:\Users\Akshit Koche\AppData\Local\Temp\ipykernel_7572\2521736421.py:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x1 = np.array(['Python', 'PHP'], dtype=np.str)
C:\Users\Akshit Koche\AppData\Local\Temp\ipykernel_7572\2521736421.py:3: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x2 = np.array([' Java', ' C++'], dtype=np.str)


# 2. Write a NumPy program to repeat all the elements three times of a given array of string
Expected Output:
Original Array:
['Python' 'PHP' 'Java' 'C++']
New array:
['PythonPythonPython' 'PHPPHPPHP' 'JavaJavaJava' 'C++C++C++']

In [2]:
import numpy as np
x1 = np.array(['Python', 'PHP', 'Java', 'C++'], dtype=np.str)
print("Original Array:")
print(x1)
new_array = np.char.multiply(x1, 3)
print("New array:")
print(new_array)


Original Array:
['Python' 'PHP' 'Java' 'C++']
New array:
['PythonPythonPython' 'PHPPHPPHP' 'JavaJavaJava' 'C++C++C++']


C:\Users\Akshit Koche\AppData\Local\Temp\ipykernel_7572\2381090376.py:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x1 = np.array(['Python', 'PHP', 'Java', 'C++'], dtype=np.str)


# 3. Write a NumPy program to capitalize the first letter, lowercase, uppercase, swapcase, title-case of all the elements of a given array.
Expected Output:
Original Array:
['python' 'PHP' 'java' 'C++']
Capitalized: ['Python' 'Php' 'Java' 'C++']
Lowered: ['python' 'php' 'java' 'c++']
Uppered: ['PYTHON' 'PHP' 'JAVA' 'C++']
Swapcased: ['PYTHON' 'php' 'JAVA' 'c++']
Titlecased: ['Python' 'Php' 'Java' 'C++']

In [3]:
import numpy as np
x = np.array(['python', 'PHP', 'java', 'C++'], dtype=np.str)
print("Original Array:")
print(x)
capitalized_case = np.char.capitalize(x)
lowered_case = np.char.lower(x)
uppered_case = np.char.upper(x)
swapcased_case = np.char.swapcase(x)
titlecased_case = np.char.title(x)
print("\nCapitalized: ", capitalized_case)
print("Lowered: ", lowered_case)
print("Uppered: ", uppered_case)
print("Swapcased: ", swapcased_case)
print("Titlecased: ", titlecased_case)


Original Array:
['python' 'PHP' 'java' 'C++']

Capitalized:  ['Python' 'Php' 'Java' 'C++']
Lowered:  ['python' 'php' 'java' 'c++']
Uppered:  ['PYTHON' 'PHP' 'JAVA' 'C++']
Swapcased:  ['PYTHON' 'php' 'JAVA' 'c++']
Titlecased:  ['Python' 'Php' 'Java' 'C++']


C:\Users\Akshit Koche\AppData\Local\Temp\ipykernel_7572\2768503590.py:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array(['python', 'PHP', 'java', 'C++'], dtype=np.str)


# 4. Write a NumPy program to make the length of each element 15 of a given array and the string centered / left-justified / right-justified with paddings of _.
Original Array:
['python exercises' 'PHP' 'java' 'C++']
Centered = ['python exercise' '______PHP______' '______java_____' '______C++______'] Left = ['python exercise' 'PHP____________' 'java___________' 'C++____________'] Right = ['python exercise' '____________PHP' '___________java' '____________C++']

In [4]:
import numpy as np
x = np.array(['python exercises', 'PHP', 'java', 'C++'], dtype=np.str)
print("Original Array:")
print(x)
centered = np.char.center(x, 15, fillchar='_')
left = np.char.ljust(x, 15, fillchar='_')
right = np.char.rjust(x, 15, fillchar='_')
print("\nCentered =", centered)
print("Left =", left)
print("Right =", right)


Original Array:
['python exercises' 'PHP' 'java' 'C++']

Centered = ['python exercise' '______PHP______' '______java_____' '______C++______']
Left = ['python exercise' 'PHP____________' 'java___________' 'C++____________']
Right = ['python exercise' '____________PHP' '___________java' '____________C++']


C:\Users\Akshit Koche\AppData\Local\Temp\ipykernel_7572\577194420.py:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array(['python exercises', 'PHP', 'java', 'C++'], dtype=np.str)


# 5. Write a NumPy program to insert a space between characters of all the elements of a given array.
Note: First array elements raised to powers from second array
Expected Output:
Original Array:
['python exercises' 'PHP' 'java' 'C++']
['p y t h o n e x e r c i s e s' 'P H P' 'j a v a' 'C + +']

In [5]:
import numpy as np
x = np.array(['python exercises', 'PHP', 'java', 'C++'], dtype=np.str)
print("Original Array:")
print(x)
r = np.char.join(" ", x)
print(r)


Original Array:
['python exercises' 'PHP' 'java' 'C++']
['p y t h o n   e x e r c i s e s' 'P H P' 'j a v a' 'C + +']


C:\Users\Akshit Koche\AppData\Local\Temp\ipykernel_7572\1351989923.py:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array(['python exercises', 'PHP', 'java', 'C++'], dtype=np.str)


# 6. Write a NumPy program to encode all the elements of a given array in cp500 and decode it again.
Sample Output:
encoded = [b'\x97\xa8\xa3\x88\x96\x95@\x85\xa7\x85\x99\x83\x89\xa2\x85\xa2'
b'\xd7\xc8\xd7' b'\x91\x81\xa5\x81' b'\xc3NN']
decoded = ['python exercises' 'PHP' 'java' 'C++']

In [6]:
import numpy as np
x = np.array(['python exercises', 'PHP', 'java', 'C++'], dtype=np.str)
print("Original Array:")
print(x)
encoded_char = np.char.encode(x, 'cp500')
decoded_char = np.char.decode(encoded_char,'cp500')
print("\nencoded =", encoded_char)
print("decoded =", decoded_char)


Original Array:
['python exercises' 'PHP' 'java' 'C++']

encoded = [b'\x97\xa8\xa3\x88\x96\x95@\x85\xa7\x85\x99\x83\x89\xa2\x85\xa2'
 b'\xd7\xc8\xd7' b'\x91\x81\xa5\x81' b'\xc3NN']
decoded = ['python exercises' 'PHP' 'java' 'C++']


C:\Users\Akshit Koche\AppData\Local\Temp\ipykernel_7572\1736441947.py:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array(['python exercises', 'PHP', 'java', 'C++'], dtype=np.str)


# 7. Write a NumPy program to remove the leading and trailing whitespaces of all the elements of a given array.
Sample output:
Original array:
[ -10.2 122.2 0.2]
Element-wise absolute value:
[ 10.2 122.2 0.2]

In [7]:
import numpy as np
x = np.array([' python exercises ', ' PHP  ', ' java  ', '  C++'], dtype=np.str)
print("Original Array:")
print(x)
stripped = np.char.strip(x)
print("\nRemove the leading and trailing whitespaces: ", stripped)


Original Array:
[' python exercises ' ' PHP  ' ' java  ' '  C++']

Remove the leading and trailing whitespaces:  ['python exercises' 'PHP' 'java' 'C++']


C:\Users\Akshit Koche\AppData\Local\Temp\ipykernel_7572\252743676.py:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array([' python exercises ', ' PHP  ', ' java  ', '  C++'], dtype=np.str)


# 8. Write a NumPy program to remove the leading whitespaces of all the elements of a given array.
Sample Output:
Original Array:
[' python exercises ' ' PHP ' ' java ' ' C++']
Remove the leading whitespaces : ['python exercises ' 'PHP ' 'java ' 'C++']

In [8]:
import numpy as np
x = np.array([' python exercises ', ' PHP  ', ' java  ', '  C++'], dtype=np.str)
print("Original Array:")
print(x)
lstripped_char = np.char.lstrip(x)
print("\nRemove the leading whitespaces : ", lstripped_char)


Original Array:
[' python exercises ' ' PHP  ' ' java  ' '  C++']

Remove the leading whitespaces :  ['python exercises ' 'PHP  ' 'java  ' 'C++']


C:\Users\Akshit Koche\AppData\Local\Temp\ipykernel_7572\1419218765.py:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array([' python exercises ', ' PHP  ', ' java  ', '  C++'], dtype=np.str)


# 9. Write a NumPy program to remove the trailing whitespaces of all the elements of a given array.
Sample Output:
Original Array:
[' python exercises ' ' PHP ' ' java ' ' C++']
Remove the trailing whitespaces : [' python exercises' ' PHP' ' java' ' C++']

In [9]:
import numpy as np
x = np.array([' python exercises ', ' PHP  ', ' java  ', '  C++'], dtype=np.str)
print("Original Array:")
print(x)
rstripped_char = np.char.rstrip(x)
print("\nRemove the trailing whitespaces : ", rstripped_char)


Original Array:
[' python exercises ' ' PHP  ' ' java  ' '  C++']

Remove the trailing whitespaces :  [' python exercises' ' PHP' ' java' '  C++']


C:\Users\Akshit Koche\AppData\Local\Temp\ipykernel_7572\203463179.py:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array([' python exercises ', ' PHP  ', ' java  ', '  C++'], dtype=np.str)


# 10. Write a NumPy program to split the element of a given array with spaces.
Sample Output:
Original Array:
['Python PHP Java C++']
Split the element of the said array with spaces:
[list(['Python', 'PHP', 'Java', 'C++'])]

In [10]:
import numpy as np
x = np.array(['Python PHP Java C++'], dtype=np.str)
print("Original Array:")
print(x)
r = np.char.split(x)
print("\nSplit the element of the said array with spaces: ")
print(r)


Original Array:
['Python PHP Java C++']

Split the element of the said array with spaces: 
[list(['Python', 'PHP', 'Java', 'C++'])]


C:\Users\Akshit Koche\AppData\Local\Temp\ipykernel_7572\1132468095.py:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array(['Python PHP Java C++'], dtype=np.str)


# 11. Write a NumPy program to split the element of a given array to multiple lines.
Sample output:
Original Array:
['Python\\Exercises, Practice, Solution']
[list(['Python\\Exercises, Practice, Solution'])]

In [11]:
import numpy as np
x = np.array(['Python\Exercises, Practice, Solution'], dtype=np.str)
print("Original Array:")
print(x)
r = np.char.splitlines(x)
print(r)


Original Array:
['Python\\Exercises, Practice, Solution']
[list(['Python\\Exercises, Practice, Solution'])]


C:\Users\Akshit Koche\AppData\Local\Temp\ipykernel_7572\4071907813.py:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array(['Python\Exercises, Practice, Solution'], dtype=np.str)


# 12. Write a NumPy program to make all the elements of a given string to a numeric string of 5 digits with zeros on its left.
Sample output:
Original Array:
['2' '11' '234' '1234' '12345']
Numeric string of 5 digits with zeros:
['00002' '00011' '00234' '01234' '12345']

In [12]:
import numpy as np
x = np.array(['2', '11', '234', '1234', '12345'], dtype=np.str)
print("\nOriginal Array:")
print(x)
r = np.char.zfill(x, 5)
print("\nNumeric string of 5 digits with zeros:")
print(r) 



Original Array:
['2' '11' '234' '1234' '12345']

Numeric string of 5 digits with zeros:
['00002' '00011' '00234' '01234' '12345']


C:\Users\Akshit Koche\AppData\Local\Temp\ipykernel_7572\3690109583.py:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array(['2', '11', '234', '1234', '12345'], dtype=np.str)


# 13. Write a NumPy program to replace "PHP" with "Python" in the element of a given array.
Sample Output:
Original Array:
['PHP Exercises, Practice, Solution']
New array:
['Python Exercises, Practice, Solution']

In [13]:
import numpy as np
x = np.array(['PHP Exercises, Practice, Solution'], dtype=np.str)
print("\nOriginal Array:")
print(x)
r = np.char.replace(x, "PHP", "Python")
print("\nNew array:")
print(r)



Original Array:
['PHP Exercises, Practice, Solution']

New array:
['Python Exercises, Practice, Solution']


C:\Users\Akshit Koche\AppData\Local\Temp\ipykernel_7572\1654307832.py:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array(['PHP Exercises, Practice, Solution'], dtype=np.str)


# 14. Write a NumPy program to test equal, not equal, greater equal, greater and less test of all the elements of two given arrays.
Expected Output:
Array1:
['Hello' 'PHP' 'JS' 'examples' 'html']
Array2:
['Hello' 'php' 'Java' 'examples' 'html']
Equal test:
[ True False False True True]
Not equal test:
[False True True False False]
Less equal test:
[ True True True True True]
Greater equal test:
[ True False False True True]
Less test:
[False True True False False]

In [14]:
import numpy as np
x1 = np.array(['Hello', 'PHP', 'JS', 'examples', 'html'], dtype=np.str)
x2 = np.array(['Hello', 'php', 'Java', 'examples', 'html'], dtype=np.str)
print("\nArray1:")
print(x1)
print("Array2:")
print(x2)
print("\nEqual test:")
r = np.char.equal(x1, x2)
print(r)
print("\nNot equal test:")
r = np.char.not_equal(x1, x2)
print(r)
print("\nLess equal test:")
r = np.char.less_equal(x1, x2)
print(r)
print("\nGreater equal test:")
r = np.char.greater_equal(x1, x2)
print(r)
print("\nLess test:")
r = np.char.less(x1, x2)
print(r)



Array1:
['Hello' 'PHP' 'JS' 'examples' 'html']
Array2:
['Hello' 'php' 'Java' 'examples' 'html']

Equal test:
[ True False False  True  True]

Not equal test:
[False  True  True False False]

Less equal test:
[ True  True  True  True  True]

Greater equal test:
[ True False False  True  True]

Less test:
[False  True  True False False]


C:\Users\Akshit Koche\AppData\Local\Temp\ipykernel_7572\637713255.py:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x1 = np.array(['Hello', 'PHP', 'JS', 'examples', 'html'], dtype=np.str)
C:\Users\Akshit Koche\AppData\Local\Temp\ipykernel_7572\637713255.py:3: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x2 = np.array(['Hello', 'php', 'Java', 'examples',

# 15. Write a NumPy program to count the number of "P" in a given array, element-wise.
Sample Output:
Original Array:
['Python' 'PHP' 'JS' 'examples' 'html']
Number of 'P':
[1 2 0 0 0]

In [15]:
import numpy as np
x1 = np.array(['Python', 'PHP', 'JS', 'examples', 'html'], dtype=np.str)
print("\nOriginal Array:")
print(x1)
print("Number of ‘P’:")
r = np.char.count(x1, "P")
print(r)



Original Array:
['Python' 'PHP' 'JS' 'examples' 'html']
Number of ‘P’:
[1 2 0 0 0]


C:\Users\Akshit Koche\AppData\Local\Temp\ipykernel_7572\99907529.py:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x1 = np.array(['Python', 'PHP', 'JS', 'examples', 'html'], dtype=np.str)


# 16. Write a NumPy program to count the lowest index of "P" in a given array, element-wise.
Original Array:
['Python' 'PHP' 'JS' 'EXAMPLES' 'HTML']
count the lowest index of 'P':
[ 0 0 -1 4 -1]

In [16]:
import numpy as np
x1 = np.array(['Python', 'PHP', 'JS', 'EXAMPLES', 'HTML'], dtype=np.str)
print("\nOriginal Array:")
print(x1)
print("count the lowest index of ‘P’:")
r = np.char.find(x1, "P")
print(r)



Original Array:
['Python' 'PHP' 'JS' 'EXAMPLES' 'HTML']
count the lowest index of ‘P’:
[ 0  0 -1  4 -1]


C:\Users\Akshit Koche\AppData\Local\Temp\ipykernel_7572\1733496685.py:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x1 = np.array(['Python', 'PHP', 'JS', 'EXAMPLES', 'HTML'], dtype=np.str)


# 17. Write a NumPy program to check whether each element of a given array is composed of digits only, lower case letters only and upper case letters only.
Sample output:
Original Array:
['Python' 'PHP' 'JS' 'Examples' 'html5' '5']
Digits only = [False False False False False True]
Lower cases only = [False False False False True False]
Upper cases only = [False True True False False False]

In [17]:
import numpy as np
x = np.array(['Python', 'PHP', 'JS', 'Examples', 'html5', '5'], dtype=np.str)
print("\nOriginal Array:")
print(x)
r1 = np.char.isdigit(x)
r2 = np.char.islower(x)
r3 = np.char.isupper(x)
print("Digits only =", r1)
print("Lower cases only =", r2)
print("Upper cases only =", r3)



Original Array:
['Python' 'PHP' 'JS' 'Examples' 'html5' '5']
Digits only = [False False False False False  True]
Lower cases only = [False False False False  True False]
Upper cases only = [False  True  True False False False]


C:\Users\Akshit Koche\AppData\Local\Temp\ipykernel_7572\3360482820.py:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array(['Python', 'PHP', 'JS', 'Examples', 'html5', '5'], dtype=np.str)


# 18. Write a NumPy program to check whether each element of a given array starts with "P".
Sample output:
Original Array:
['Python' 'PHP' 'JS' 'examples' 'html']
Test if each element of the said array starts with 'P':
[ True True False False False]

In [18]:
import numpy as np
x1 = np.array(['Python', 'PHP', 'JS', 'examples', 'html'], dtype=np.str)
print("\nOriginal Array:")
print(x1)
print("Test if each element of the said array starts with 'P':")
r = np.char.startswith(x1, "P")
print(r)



Original Array:
['Python' 'PHP' 'JS' 'examples' 'html']
Test if each element of the said array starts with 'P':
[ True  True False False False]


C:\Users\Akshit Koche\AppData\Local\Temp\ipykernel_7572\3651875122.py:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x1 = np.array(['Python', 'PHP', 'JS', 'examples', 'html'], dtype=np.str)


# 19. Write a NumPy program to add two zeros to the beginning of each element of a given array of string values.
Sample output:
Original array:
['1.12' '2.23' '3.71' '4.23' '5.11']
Add two zeros to the beginning of each element of the said array:
['001.12' '002.23' '003.71' '004.23' '005.11']
Alternate method:
['001.12' '002.23' '003.71' '004.23' '005.11']

In [19]:
import numpy as np 

nums = np.array(['1.12', '2.23', '3.71', '4.23', '5.11'], dtype=np.str)
print("Original array:")
print(nums)
print("\nAdd two zeros to the beginning of each element of the said array:")
print(np.char.add('00', nums))
print("\nAlternate method:")
print(np.char.rjust(nums, 6, fillchar='0'))


Original array:
['1.12' '2.23' '3.71' '4.23' '5.11']

Add two zeros to the beginning of each element of the said array:
['001.12' '002.23' '003.71' '004.23' '005.11']

Alternate method:
['001.12' '002.23' '003.71' '004.23' '005.11']


C:\Users\Akshit Koche\AppData\Local\Temp\ipykernel_7572\1570248876.py:3: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  nums = np.array(['1.12', '2.23', '3.71', '4.23', '5.11'], dtype=np.str)


# 20. Write a NumPy program to replace a specific character with another in a given array of string values.
Sample output:
Original array of string values:
[['Python-NumPy-Exercises']
['-Python-']]
Replace '-' with '=' character in the said array of string values:
[['Python==NumPy==Exercises']
['==Python==']]
Replace '-' with ' ' character in the said array of string values:
[['Python NumPy Exercises']
['Python']]

In [20]:
import numpy as np 

str1 = np.array([['Python-NumPy-Exercises'],
              ['-Python-']])
print("Original array of string values:") 
print(str1)
print("\nReplace '-' with '=' character in the said array of string values:")
print(np.char.strip(np.char.replace(str1, '-', '==')))
print("\nReplace '-' with ' ' character in the said array of string values:")
print(np.char.strip(np.char.replace(str1, '-', ' ')))


Original array of string values:
[['Python-NumPy-Exercises']
 ['-Python-']]

Replace '-' with '=' character in the said array of string values:
[['Python==NumPy==Exercises']
 ['==Python==']]

Replace '-' with ' ' character in the said array of string values:
[['Python NumPy Exercises']
 ['Python']]


# 21. Write a NumPy program to count a given word in each row of a given array of string values.
Sample output:
Original array of string values:
[['Python' 'NumPy' 'Exercises']
['Python' 'Pandas' 'Exercises']
['Python' 'Machine learning' 'Python']]
Count 'Python' row wise in the above array of string values:
[[1 0 0]
[1 0 0]
[1 0 1]]

In [21]:
import numpy as np 

str1 = np.array([['Python','NumPy','Exercises'],
                 ['Python','Pandas','Exercises'],
                 ['Python','Machine learning','Python']])
print("Original array of string values:") 
print(str1)
print("\nCount 'Python' row wise in the above array of string values:")
print(np.char.count(str1, 'Python'))


Original array of string values:
[['Python' 'NumPy' 'Exercises']
 ['Python' 'Pandas' 'Exercises']
 ['Python' 'Machine learning' 'Python']]

Count 'Python' row wise in the above array of string values:
[[1 0 0]
 [1 0 0]
 [1 0 1]]


# 22. Write a NumPy program to split a given text into lines and split the single line into array values.
Sample output:
Original text:
01 V Debby Pramod
02 V Artemiy Ellie
03 V Baptist Kamal
04 V Lavanya Davide
05 V Fulton Antwan
06 V Euanthe Sandeep
07 V Endzela Sanda
08 V Victoire Waman
09 V Briar Nur
10 V Rose Lykos
Array from the said text:
[['01' 'V' 'Debby Pramod']
['02' 'V' 'Artemiy Ellie']
['03' 'V' 'Baptist Kamal']
['04' 'V' 'Lavanya Davide']
['05' 'V' 'Fulton Antwan']
['06' 'V' 'Euanthe Sandeep']
['07' 'V' 'Endzela Sanda']
['08' 'V' 'Victoire Waman']
['09' 'V' 'Briar Nur']
['10' 'V' 'Rose Lykos']]



In [22]:
import numpy as np 
student = """01	V	Debby Pramod
02	V	Artemiy Ellie
03	V	Baptist Kamal
04	V	Lavanya Davide
05	V	Fulton Antwan
06	V	Euanthe Sandeep
07	V	Endzela Sanda
08	V	Victoire Waman
09	V	Briar Nur
10	V	Rose Lykos"""

print("Original text:") 
print(student)
text_lines = student.splitlines()
text_lines = [r.split('\t') for r in text_lines]
result = np.array(text_lines, dtype=np.str)
print("\nArray from the said text:")
print(result)


Original text:
01	V	Debby Pramod
02	V	Artemiy Ellie
03	V	Baptist Kamal
04	V	Lavanya Davide
05	V	Fulton Antwan
06	V	Euanthe Sandeep
07	V	Endzela Sanda
08	V	Victoire Waman
09	V	Briar Nur
10	V	Rose Lykos

Array from the said text:
[['01' 'V' 'Debby Pramod']
 ['02' 'V' 'Artemiy Ellie']
 ['03' 'V' 'Baptist Kamal']
 ['04' 'V' 'Lavanya Davide']
 ['05' 'V' 'Fulton Antwan']
 ['06' 'V' 'Euanthe Sandeep']
 ['07' 'V' 'Endzela Sanda']
 ['08' 'V' 'Victoire Waman']
 ['09' 'V' 'Briar Nur']
 ['10' 'V' 'Rose Lykos']]


C:\Users\Akshit Koche\AppData\Local\Temp\ipykernel_7572\3964312263.py:17: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  result = np.array(text_lines, dtype=np.str)


# NumPy: String Exercises is Completed.