# 1. Write a NumPy program to compute the multiplication of two given matrixes.

In [1]:
import numpy as np
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print("original matrix:")
print(p)
print(q)
result1 = np.dot(p, q)
print("Result of the said matrix multiplication:")
print(result1)


original matrix:
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
Result of the said matrix multiplication:
[[1 2]
 [3 4]]


# 2. Write a NumPy program to compute the outer product of two given vectors.

In [2]:
import numpy as np
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print("original matrix:")
print(p)
print(q)
result = np.outer(p, q)
print("Outer product of the said two vectors:")
print(result)


original matrix:
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
Outer product of the said two vectors:
[[1 2 3 4]
 [0 0 0 0]
 [0 0 0 0]
 [1 2 3 4]]


# 3. Write a NumPy program to compute the cross product of two given vectors.

In [3]:
import numpy as np
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print("original matrix:")
print(p)
print(q)
result1 = np.cross(p, q)
result2 = np.cross(q, p)
print("cross product of the said two vectors(p, q):")
print(result1)
print("cross product of the said two vectors(q, p):")
print(result2)


original matrix:
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
cross product of the said two vectors(p, q):
[ 2 -3]
cross product of the said two vectors(q, p):
[-2  3]


# 4. Write a NumPy program to compute the determinant of a given square array.

In [4]:
import numpy as np
from numpy import linalg as LA
a = np.array([[1, 0], [1, 2]])
print("Original 2-d array")
print(a)
print("Determinant of the said 2-D array:")
print(np.linalg.det(a))


Original 2-d array
[[1 0]
 [1 2]]
Determinant of the said 2-D array:
2.0


# 5. Write a NumPy program to evaluate Einstein's summation convention of two given multidimensional arrays.

In [5]:
import numpy as np
a = np.array([1,2,3])
b = np.array([0,1,0])
print("Original 1-d arrays:")
print(a)
print(b)
result =  np.einsum("n,n", a, b)
print("Einstein’s summation convention of the said arrays:")
print(result)
x = np.arange(9).reshape(3, 3)
y = np.arange(3, 12).reshape(3, 3)
print("Original Higher dimension:")
print(x)
print(y)
result = np.einsum("mk,kn", x, y)
print("Einstein’s summation convention of the said arrays:")
print(result)


Original 1-d arrays:
[1 2 3]
[0 1 0]
Einstein’s summation convention of the said arrays:
2
Original Higher dimension:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Einstein’s summation convention of the said arrays:
[[ 24  27  30]
 [ 78  90 102]
 [132 153 174]]


# 6. Write a NumPy program to compute the inner product of vectors for 1-D arrays (without complex conjugation) and in higher dimension.

In [6]:
import numpy as np
a = np.array([1,2,5])
b = np.array([2,1,0])
print("Original 1-d arrays:")
print(a)
print(b)
print 
result = np.inner(a, b)
print("Inner product of the said vectors:")
x = np.arange(9).reshape(3, 3)
y = np.arange(3, 12).reshape(3, 3)
print("Higher dimension arrays:")
print(x)
print(y)
result = np.inner(x, y)
print("Inner product of the said vectors:")
print(result)


Original 1-d arrays:
[1 2 5]
[2 1 0]
Inner product of the said vectors:
Higher dimension arrays:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Inner product of the said vectors:
[[ 14  23  32]
 [ 50  86 122]
 [ 86 149 212]]


# 7. Write a NumPy program to compute the eigenvalues and right eigenvectors of a given square array.

In [7]:
import numpy as np
m = np.mat("3 -2;1 0")
print("Original matrix:")
print("a\n", m)
w, v = np.linalg.eig(m) 
print( "Eigenvalues of the said matrix",w)
print( "Eigenvectors of the said matrix",v)


Original matrix:
a
 [[ 3 -2]
 [ 1  0]]
Eigenvalues of the said matrix [2. 1.]
Eigenvectors of the said matrix [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


# 8. Write a NumPy program to compute the Kronecker product of two given mulitdimension arrays.

In [8]:
import numpy as np
a = np.array([1,2,3])
b = np.array([0,1,0])
print("Original 1-d arrays:")
print(a)
print(b)
result =  np.kron(a, b)
print("Kronecker product of the said arrays:")
print(result)
x = np.arange(9).reshape(3, 3)
y = np.arange(3, 12).reshape(3, 3)
print("Original Higher dimension:")
print(x)
print(y)
result = np.kron(x, y)
print("Kronecker product  of the said arrays:")
print(result)


Original 1-d arrays:
[1 2 3]
[0 1 0]
Kronecker product of the said arrays:
[0 1 0 0 2 0 0 3 0]
Original Higher dimension:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Kronecker product  of the said arrays:
[[ 0  0  0  3  4  5  6  8 10]
 [ 0  0  0  6  7  8 12 14 16]
 [ 0  0  0  9 10 11 18 20 22]
 [ 9 12 15 12 16 20 15 20 25]
 [18 21 24 24 28 32 30 35 40]
 [27 30 33 36 40 44 45 50 55]
 [18 24 30 21 28 35 24 32 40]
 [36 42 48 42 49 56 48 56 64]
 [54 60 66 63 70 77 72 80 88]]


# 9. Write a NumPy program to compute the condition number of a given matrix.

In [9]:
import numpy as np
v = np.arange(7)
result = np.linalg.norm(v)
print("Vector norm:")
print(result)
m = np.matrix('1, 2; 3, 4') 
result1 = np.linalg.norm(m)
print("Matrix norm:")
print(result1)


Vector norm:
9.539392014169456
Matrix norm:
5.477225575051661


# 10. Write a NumPy program to find a matrix or vector norm.

In [10]:
import numpy as np
v = np.arange(7)
result = np.linalg.norm(v)
print("Vector norm:")
print(result)
m = np.matrix('1, 2; 3, 4') 
result1 = np.linalg.norm(m)
print("Matrix norm:")
print(result1)


Vector norm:
9.539392014169456
Matrix norm:
5.477225575051661


# 11. Write a NumPy program to compute the determinant of an array.

In [11]:
import numpy as np
a = np.array([[1,2],[3,4]])
print("Original array:")
print(a)
result =  np.linalg.det(a)
print("Determinant of the said array:")
print(result)


Original array:
[[1 2]
 [3 4]]
Determinant of the said array:
-2.0000000000000004


# 12. Write a NumPy program to compute the inverse of a given matrix.

In [12]:
import numpy as np
m = np.array([[1,2],[3,4]])
print("Original matrix:")
print(m)
result =  np.linalg.inv(m)
print("Inverse of the said matrix:")
print(result)


Original matrix:
[[1 2]
 [3 4]]
Inverse of the said matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]


# 13. Write a NumPy program to calculate the QR decomposition of a given matrix.

In [13]:
import numpy as np
m = np.array([[1,2],[3,4]])
print("Original matrix:")
print(m)
result =  np.linalg.qr(m)
print("Decomposition of the said matrix:")
print(result)


Original matrix:
[[1 2]
 [3 4]]
Decomposition of the said matrix:
(array([[-0.31622777, -0.9486833 ],
       [-0.9486833 ,  0.31622777]]), array([[-3.16227766, -4.42718872],
       [ 0.        , -0.63245553]]))


# 14. Write a NumPy program to compute the condition number of a given matrix.

In [14]:
import numpy as np
m = np.array([[1,2],[3,4]])
print("Original matrix:")
print(m)
result =  np.linalg.cond(m)
print("Condition number of the said matrix:")
print(result)


Original matrix:
[[1 2]
 [3 4]]
Condition number of the said matrix:
14.933034373659268


# 15. Write a NumPy program to compute the sum of the diagonal element of a given array.

In [15]:
import numpy as np
m = np.arange(6).reshape(2,3)
print("Original matrix:")
print(m)
result =  np.trace(m)
print("Condition number of the said matrix:")
print(result)


Original matrix:
[[0 1 2]
 [3 4 5]]
Condition number of the said matrix:
4


# 16. Write a NumPy program to get the lower-triangular L in the Cholesky decomposition of a given array.

In [16]:
import numpy as np
a = np.array([[4, 12, -16], [12, 37, -53], [-16, -53, 98]], dtype=np.int32)
print("Original array:")
print(a)
L = np.linalg.cholesky(a)
print("Lower-trianglular L in the Cholesky decomposition of the said array:")
print(L)


Original array:
[[  4  12 -16]
 [ 12  37 -53]
 [-16 -53  98]]
Lower-trianglular L in the Cholesky decomposition of the said array:
[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8. -5.  3.]]


# 17. Write a NumPy program to get the qr factorization of a given array.

In [17]:
import numpy as np
a = np.array([[4, 12, -14], [12, 37, -53], [-14, -53, 98]], dtype=np.int32)
print("Original array:")
print(a)
q, r = np.linalg.qr(a)
print("qr factorization of the said array:")
print( "q=\n", q, "\nr=\n", r)


Original array:
[[  4  12 -14]
 [ 12  37 -53]
 [-14 -53  98]]
qr factorization of the said array:
q=
 [[-0.21199958 -0.27930103  0.93650794]
 [-0.63599873 -0.68815735 -0.34920635]
 [ 0.74199852 -0.66964945 -0.03174603]] 
r=
 [[-18.86796226 -65.4018692  109.39178122]
 [  0.           6.67798664 -25.24309237]
 [  0.           0.           2.28571429]]


# 18. Write a NumPy program to compute the factor of a given array by Singular Value Decomposition.

In [18]:
import numpy as np
a = np.array([[1, 0, 0, 0, 2], [0, 0, 3, 0, 0], [0, 0, 0, 0, 0], [0, 2, 0, 0, 0]], dtype=np.float32)
print("Original array:")
print(a)
U, s, V = np.linalg.svd(a, full_matrices=False)
q, r = np.linalg.qr(a)
print("Factor of a given array  by Singular Value Decomposition:")
print("U=\n", U, "\ns=\n", s, "\nV=\n", V)


Original array:
[[1. 0. 0. 0. 2.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]]
Factor of a given array  by Singular Value Decomposition:
U=
 [[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  1.  0.]] 
s=
 [3.       2.236068 2.       0.      ] 
V=
 [[-0.         0.         1.        -0.         0.       ]
 [ 0.4472136 -0.        -0.        -0.         0.8944272]
 [-0.         1.         0.        -0.         0.       ]
 [ 0.         0.         0.         1.         0.       ]]


# 19. Write a NumPy program to calculate the Frobenius norm and the condition number of a given array.

In [19]:
import numpy as np
a = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(a)
print("Frobenius norm and the condition number:")
print(np.linalg.norm(a, 'fro'))
print(np.linalg.cond(a, 'fro'))


Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Frobenius norm and the condition number:
16.881943016134134
4.561770736605098e+17


# NumPy Linear Algebra: Exercises is Completed.